# Generated by Django 5.2 on 2025-05-30 21:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_course_classsession_assigment_schedule_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='materials/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'pptx', 'jpg', 'png'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='dashboard.classsession')),
            ],
        ),
    ]
